      SUBROUTINE VUMAT(
C READ ONLY (UNMODIFIABLE) VARIABLES -
     1  NBLOCK, NDIR, NSHR, NSTATEV, NFIELDV, NPROPS, JINFOARRAY,
     2  STEPTIME, TOTALTIME, DTARRAY, CMNAME, COORDMP, CHARLENGTH,
     3  PROPS, DENSITY, STRAININC, RELSPININC,
     4  TEMPOLD, STRETCHOLD, DEFGRADOLD, FIELDOLD,
     5  STRESSOLD, STATEOLD, ENERINTERNOLD, ENERINELASOLD,
     6  TEMPNEW, STRETCHNEW, DEFGRADNEW, FIELDNEW,
C WRITE ONLY (MODIFIABLE) VARIABLES -
     7  STRESSNEW, STATENEW, ENERINTERNNEW, ENERINELASNEW )

      INCLUDE 'vaba_param.inc'

      CHARACTER*80 CMNAME

      DIMENSION PROPS(NPROPS)
      DIMENSION DENSITY(NBLOCK)
      DIMENSION STRAININC(NBLOCK,NDIR+NSHR)
      DIMENSION STRESSOLD(NBLOCK,NDIR+NSHR)
      DIMENSION STRESSNEW(NBLOCK,NDIR+NSHR)
      DIMENSION STATEOLD(NBLOCK,NSTATEV)
      DIMENSION STATENEW(NBLOCK,NSTATEV)

      DOUBLE PRECISION E, NU, MU, LAMBDA, TRACE
      INTEGER I, J

C     Material parameters
      E  = PROPS(1)
      NU = PROPS(2)

      MU     = E / (2.D0*(1.D0 + NU))
      LAMBDA = E*NU / ((1.D0 + NU)*(1.D0 - 2.D0*NU))

      WRITE(6,*) 'DENSITY=',DENSITY(1)
      WRITE(6,*) 'E=',E,'nu=',NU
      WRITE(6,*) 'MU=',MU,'LAMBDA=',LAMBDA

C     Loop over material points
      DO I = 1, NBLOCK

        WRITE(6,*) 'I=',I
        TRACE = 0.D0
        DO J = 1, NDIR
          TRACE = TRACE + STRAININC(I,J)
        END DO

C       Normal stresses
        DO J = 1, NDIR
          STRESSNEW(I,J) = STRESSOLD(I,J)
     &      + LAMBDA*TRACE
     &      + 2.D0*MU*STRAININC(I,J)
        END DO

C       Shear stresses
        DO J = NDIR+1, NDIR+NSHR
          STRESSNEW(I,J) = STRESSOLD(I,J)
     &      + 2.D0*MU*STRAININC(I,J)
        END DO

      END DO

      RETURN
      END
